### ISSUE TITLE
Microservice Challenge : Starter

### ISSUE THREAD

**Issue by vinodmrhcl** [ERS-HCL/microservice-starter#1]
An effort to create a micro-services starter collection based on various tools/frameworks available in market. viz. 

- [x] Spring Boot
- [x] Tomcat
- [x] Jetty
- [x] Grizzly
- [x] Netty
- [x] JBoss Undertow
- [x] Wildfly Swarm

**Comment by tsukhu** [comment]
@vinodmrhcl  - Please make sure the project adds value beyond just the basic setup that the standard guides provide. Also the README of each of the projects MUST answer why is this project required and who will benefit from it.

**Comment by vinodmrhcl** [comment]
Implemented starters for all the popular tools/framework.
